import type { AnalyticsData, DateRange } from "@/types/analytics";

export const DEFAULT_DATE_RANGE: DateRange = {
  from: new Date("2026-05-06T00:00:00+05:30"),
  to: new Date("2026-06-06T00:00:00+05:30"),
  label: "May 6 – Jun 6, 2026",
};

export const dummyAnalyticsData: AnalyticsData = {
  kpis: [
    {
      id: "k1",
      title: "Total Views",
      value: 553,
      change: "↑18.5% vs previous",
      trend: "up",
      icon: "eye",
      bgColor: "bg-teal-50",
      iconColor: "text-brand-primary",
    },
    {
      id: "k2",
      title: "Total Bookmarks",
      value: 342,
      change: "↑12.7% vs previous",
      trend: "up",
      icon: "bookmark",
      bgColor: "bg-blue-50",
      iconColor: "text-blue-600",
    },
    {
      id: "k3",
      title: "Total Messages",
      value: 67,
      change: "↓5.3% vs previous",
      trend: "down",
      icon: "message",
      bgColor: "bg-orange-50",
      iconColor: "text-orange-600",
    },
    {
      id: "k4",
      title: "Successful Deals",
      value: 24,
      change: "↑9.1% vs previous",
      trend: "up",
      icon: "deal",
      bgColor: "bg-purple-50",
      iconColor: "text-purple-600",
    },
  ],
  chartData: [
    { date: "May 6", views: 120, previous: 90 },
    { date: "May 11", views: 180, previous: 140 },
    { date: "May 16", views: 220, previous: 170 },
    { date: "May 21", views: 300, previous: 210 },
    { date: "May 26", views: 260, previous: 240 },
    { date: "May 31", views: 340, previous: 280 },
    { date: "Jun 6", views: 410, previous: 320 },
  ],
  insights: [
    {
      id: "i1",
      icon: "eye",
      title: "Most Viewed Book",
      subtitle: "Introduction to Algorithms",
      metric: "89 Views",
    },
    {
      id: "i2",
      icon: "bookmark",
      title: "Most Bookmarked Book",
      subtitle: "The Alchemist",
      metric: "34 Bookmarks",
    },
    {
      id: "i3",
      icon: "category",
      title: "Best Performing Category",
      subtitle: "Computer Science",
      metric: "142 Views",
    },
    {
      id: "i4",
      icon: "conversion",
      title: "Conversion Rate",
      subtitle: "Views → Successful Deals",
      metric: "4.3%",
      trend: "↑1.2%",
      trendUp: true,
    },
  ],
  activeListings: [
    { id: "l1", title: "Introduction to Algorithms", status: "active" },
    { id: "l2", title: "Clean Code", status: "active" },
    { id: "l3", title: "Design Patterns", status: "attention" },
    { id: "l4", title: "The Pragmatic Programmer", status: "active" },
  ],
  topPerformers: [
    {
      id: "b1",
      rank: 1,
      title: "Introduction to Algorithms",
      category: "Computer Science",
      views: 89,
      bookmarks: 34,
      messages: 12,
      revenue: 850,
      soldCount: 12,
    },
    {
      id: "b2",
      rank: 2,
      title: "Clean Code",
      category: "Software Engineering",
      views: 76,
      bookmarks: 28,
      messages: 9,
      revenue: 620,
      soldCount: 8,
    },
    {
      id: "b3",
      rank: 3,
      title: "The Pragmatic Programmer",
      category: "Software Engineering",
      views: 64,
      bookmarks: 22,
      messages: 7,
      revenue: 490,
      soldCount: 6,
    },
    {
      id: "b4",
      rank: 4,
      title: "Design Patterns",
      category: "Computer Science",
      views: 58,
      bookmarks: 19,
      messages: 6,
      revenue: 410,
      soldCount: 5,
    },
  ],
  recentActivity: [
    { id: "a1", icon: "eye", title: "Your book Introduction to Algorithms was viewed", timestamp: "5m ago" },
    { id: "a2", icon: "bookmark", title: "The Alchemist was bookmarked", timestamp: "12m ago" },
    { id: "a3", icon: "message", title: "New message from Jatin Mehta", timestamp: "25m ago" },
    { id: "a4", icon: "eye", title: "Deep Work was viewed", timestamp: "1h ago" },
    { id: "a5", icon: "deal", title: "Sapiens was sold", timestamp: "2h ago" },
  ],
};
